#pragma once

extern "C" {
  #include "hw_gpio.h"
}

#define HAPTIC_PORT HW_GPIO_PORT_4
#define HAPTIC_PIN  HW_GPIO_PIN_1

#define UART_TX_PORT HW_GPIO_PORT_1
#define UART_TX_PIN  HW_GPIO_PIN_3
#define UART_RX_PORT HW_GPIO_PORT_2
#define UART_RX_PIN  HW_GPIO_PIN_3

#define IMU_INT1_PORT HW_GPIO_PORT_3
#define IMU_INT1_PIN HW_GPIO_PIN_6

#define BUTTON_PORT HW_GPIO_PORT_3
#define BUTTON_PIN HW_GPIO_PIN_7

#define RFID_UART_TX_PORT HW_GPIO_PORT_4
#define RFID_UART_TX_PIN HW_GPIO_PIN_4
#define RFID_UART_RX_PORT HW_GPIO_PORT_4
#define RFID_UART_RX_PIN HW_GPIO_PIN_5
#define RFID_VPD_PORT HW_GPIO_PORT_4
#define RFID_VPD_PIN HW_GPIO_PIN_0
#define RFID_ENABLE_PORT HW_GPIO_PORT_4
#define RFID_ENABLE_PIN HW_GPIO_PIN_3

#define I2C1_SDA_PORT HW_GPIO_PORT_4
#define I2C1_SDA_PIN HW_GPIO_PIN_6
#define I2C1_SCL_PORT HW_GPIO_PORT_4
#define I2C1_SCL_PIN HW_GPIO_PIN_7
